barkbank/barkbank-pawtal

db/schema.sql, src/lib/data/dbAdmins.ts, src/lib/data/dbDogs.ts, src/lib/data/dbUsers.ts, src/lib/data/dbVets.ts
The schema now specifies CURRENT_TIMESTAMP as default value for all creation_time columns.
=> CreationTime - Update insertions to not set creation time

src/lib/bark-utils.ts, src/lib/data/mappers.ts, src/lib/stringutils.ts, tests/SecretEncryptionService.test.ts, tests/dbLayer.test.ts
Changes
(1) Refactored the tests in `dbLayer.test.ts` to be grouped by their respective module and function. E.g. dbUsers/dbInsertUser. While the original plan was to split `dbLayer.test.ts` into files like `dbUsers.test.ts`, we decided against this so that the fixtures (currently private) do not need to be exported from some common file.
(2) A bug in mappers.ts was fixed. Great!
(3) The `guaranteed()` function from `stringutils.ts` has been made generic for any type T. Consequently, module has been renamed to `bark-utils.ts`. The reason for the `bark-` prefix is because there's an existing `utils.ts`—I believe it was inserted by shadcn-ui.
=> RefactorDbLayerTests - Refactor the tests in dbLayer.test.ts

src/app/api/dangerous/admins/route.ts, src/lib/admin/admin-actor.ts, src/lib/auth.ts, src/lib/data/db-models.ts, tests/AdminActor.test.ts, tests/AdminActorFactory.test.ts, tests/UserActor.test.ts, tests/UserActorFactory.test.ts, tests/VetActorFactory.test.ts, tests/_fixtures.ts
Changes
(1) Methods for checking admin permissions were implemented for the AdminActor. E.g. canManageAdminAccounts
(2) The getOwnAdmin method now caches the Promise, so that calls to different canFoo canBar methods do not result in multiple database fetches.
(3) Minor refactoring. Prettier formatting, renaming createFoo to insertFoo in fixtures, and removing unused imports.
=> AdminCan - Implement AdminActor canThis canThat methods.

src/app/user/registration/_lib/get-vet-options.ts, src/app/user/registration/page.tsx, src/components/bark/bark-form.tsx, tests/_fixtures.ts, tests/get-vet-options.test.ts
(1) Feature - Vet addresses are now rendered below the vet name. The BarkFormOption type was extended to include an optional `description` to support this. When `description` is specified, a FormDescription is rendered below the FormLabel. Currently this only works for radio groups.
(2) Testing - The function for querying the database is moved into ./_lib/get-vet-options so its getVetOptions function can be tested.
(3) Refactoring - The manner by which the async retrievals for breed list and vet options are orchestrated is improved.
=> Improved Vet Options for Registration Form

src/lib/data/db-dogs.ts, src/lib/user/actions/get-my-dog-details.ts, src/lib/user/user-models.ts, tests/_fixtures.ts, tests/user/get-my-dog-details.test.ts
Extend the MyDogDetails object returned by getMyDogDetails to include the following fields:
* dogParticipationStatus
* dogPauseExpiryTime
* dogPreferredVetId
These are to support the form pre-fill needs of the /user/my-pet/dogs/[dogId]/edit page.
=> More fields for my dog details

e2e/user-my-pets.spec.ts, scripts/setup-dev-data.js, src/app/_components/header-items.tsx, src/app/user/(logged-in)/my-pets/page.tsx, src/components/bark/bark-sidebar.tsx
Changes for my-pets
- use rounded cards for each pet in the my-pets list
- update the layout for mobile and desktop
Changes for sidebar
- adjust breakpoint to md. This makes it consistent with itself and with the nav bar.
Changes for nav bar
- split the mobile and desktop variants into two different sub-components
- move hamburger menu to right side for mobile variant.
In aggregate, this fixes the problem where sometimes the nav bar is shorter than the content.
=> Dog Cards, Nav Bar, and Side Bar

Makefile, e2e/_ui_test_helpers.ts, e2e/footer.spec.ts, e2e/nav-bar.spec.ts, e2e/root-page.spec.ts, e2e/user-login-page.spec.ts, e2e/user-my-account.spec.ts, e2e/user-my-pets.spec.ts, e2e/user-sidebar.spec.ts, scripts/test_no_wip_tasks_remaining.sh, src/app/_components/header-items.tsx, src/app/_components/root-footer.tsx, src/app/_components/root-header.tsx, src/app/admin/(logged-in)/layout.tsx, src/app/page.tsx, src/app/user/(logged-in)/layout.tsx, src/app/user/login/page.tsx, src/app/vet/(logged-in)/layout.tsx, src/components/bark/bark-form.tsx, src/components/bark/bark-sidebar.tsx, src/components/bark/login/bark-login-form.tsx, src/components/bark/login/bark-login-page.tsx, src/lib/route-path.ts, tests/RoutePath.test.ts
nav items
- reduced nav bar items to just visit website and visit faq
logout
- show logout in nav bar when logged-in.
- remove logout sidebar option
user sidebar
- add criteria and process options - currently dead links
root page
- redirects to user login page when not logged-in
- redirects to the account specific default landing page when logged-in
login page
- removed the cancel button (since it no longer makes sense, given the changes to root page above)
footer
- add links to admin and vet login, but only when the user is not logged-in.
Makefile
- new make all target to run all the tests
- test-ui now only uses chromium and Mobile Chome
=> Revised Navigation

Makefile, e2e/nav-bar.spec.ts, src/app/_components/header-items.tsx
Changes
- use larger fonts and gaps in the nav menu so that it is easier to tap with fingers.
- close the nav menu after an option is selected
- run test-ui with 1 worker (can choose more using pw_worker=4, for example)
=> Bigger fonts and gaps for nav menu

src/app/user/(logged-in)/my-account/page.tsx
The icons are of different shapes. Yet when we set the dimensions to the exact values from the SVG files, the alignment with the text alongside on the right goes haywire. Thus we put the icons in a 25x25 div and apply full/auto on width/height as appropriate. Now, all of these styling is very verbose. So the icons and values are put into a `userDetails` array and rendered consistently using `map()`.
=> Fix icon scaling in my account page

src/app/user/(logged-in)/my-account/page.tsx, src/app/user/(logged-in)/my-pets/page.tsx, src/components/bark/bark-sidebar.tsx
In view of the design for /user/info, where there is a section with coloured background that's flush to the left and right sides of the page, this commit removes the padding that the sidebar layout used to place around the main content. Each page should not be responsible for adding their own padding or margins.
=> Update sidebar layout to no longer add padding around main content

src/lib/vet/actions/get-available-dogs.ts, tests/vet/get-available-dogs.test.ts
Previously call_outcome APPOINTMENT was not considered. Thus calls with outcomes like DECLINED that would never have a report got counted as an appointment pending report. This mistake omits dogs that would otherise be available from the response.
=> Fix the getAvailableDogs query

Makefile, db/V2__ref_tables.sql, db/V4__ref_latest_values.sql, e2e/_lib/register-test-user.ts, src/lib/user/actions/update-dog-profile.ts, src/lib/user/actions/update-sub-profile.ts, tests/_fixtures.ts, tests/schema/latest-values.test.ts, tests/user/get-dog-profile.test.ts, tests/user/update-dog-profile.test.ts, tests/user/update-sub-profile.test.ts
(1) This commit fixes the way latest weight is resolved.
(1.1) Correct way is to use the latest value from EITHER the "dogs" table or from the "reports" table.
(1.2) The wrong way, which this fixes was to prefer the latest value from the "reports" table.
(2) To fix this, a new "profile_modification_time" column had to be added to the "dogs" table. This column defaults to CURRENT_TIMESTAMP. So it is set automatically upon insertion. Subsequently, it is updated to CURRENT_TIMESTAMP by updateDogProfile and updateSubProfile. The column is then used in the "latest_values" view to resolve the correct "latest_dog_weight_kg". (Related to barkbank-schema migrations V32 and V33.)
=> Resolve latest weight correctly

src/app/layout.tsx, src/components/bark/bark-form.tsx, src/components/bark/login/bark-login-form.tsx
(1) When the font size of a text input is under 16px, iOS Safari will zoom into the text input when it is focused. This breaks the mobile webapp experience because when the user is done entering their information, they have to manually zoom out.
(2) This commit solves the problem by using "text-base" Tailwind CSS class to set the font size to 16px. This is done for BarkFormInput and BarkFormDateInput.
=> Improve accessibility so iOS Safari does not zoom in on text inputs

e2e/_lib/pom/core/pom-dynamic-page.ts, e2e/_lib/pom/core/pom-page.ts, e2e/_lib/pom/init/register-test-user.ts, e2e/_lib/pom/pages/user-edit-dog-page.ts, e2e/_lib/pom/pages/user-my-pets-page.ts, e2e/user/user-can-cancel-edit-dog.spec.ts, e2e/user/user-can-edit-dog.spec.ts, src/app/user/(logged-in)/my-pets/add-dog/_actions/submit-dog.ts, src/app/user/(logged-in)/my-pets/dogs/[dogId]/edit/_actions/update-dog-profile-action.ts, src/app/user/(logged-in)/my-pets/dogs/[dogId]/edit/_components/edit-dog-profile-form.tsx, src/app/user/(logged-in)/my-pets/dogs/[dogId]/edit/page.tsx, src/app/user/(logged-in)/my-pets/page.tsx, src/components/ui/button.tsx, src/lib/route-path.ts, tests/RoutePath.test.ts
(1) This commit implements the User Edit Dog Page.
(2) Details about the implementation:
-(a) It is built on the GeneralDogForm.
-(b) Pre-filled data is taken from getDogProfile.
(3) Other changes:
-(a) A PomDynamicPage abstraction was introduced for pages like Edit Dog where the URL is a dynamic route.
-(b) Route paths for edit and view dog were updated to include "my-pets". This way the navigation component can mark the correct nav-route as active.
-(c) revalidatePath for My Pets is now done at the "layout" level (Ref1). The reason for this is so that My Pets and View Dog can be revalidated. At least I think this is how it works. We should update the Edit Dog test to verify this. A TODO comment is left in the test to check this in future.
Ref1: …
=> User Edit Dog Page

.github/workflows/test-ui.yml, e2e/_lib/pom/init/register-test-user.ts, e2e/_lib/pom/pages/user-registration-page.ts, e2e/visitor/visitor-can-register.spec.ts
(1) Test the user registration flow.
(2) Details
—(a) A UserRegistrationPage POM was defined.
—(b) A visitor-can-register scenario was written using the UserRegistrationPage POM.
—(c) The register-test-user init function was updated to use the new UserRegistrationPage POM.
(3) Other changes
—(a) Use matrix strategy to run chromium and mobile chrome tests in parallel.
=> test visitor-can-register

package-lock.json, package.json, src/app/_lib/toast-delay.ts, src/app/layout.tsx, src/app/user/(logged-in)/my-pets/add-dog/_components/add-dog-form.tsx, src/app/user/(logged-in)/my-pets/edit-dog/[dogId]/_actions/post-dog-profile-update.ts, src/app/user/(logged-in)/my-pets/edit-dog/[dogId]/_components/edit-dog-profile-form.tsx, src/components/ui/toast.tsx, src/components/ui/toaster.tsx, src/components/ui/use-toast.ts
(1) Sometimes it can take awhile for data to get into the database. (Another issue!) So, in the frontend we want to indicate when data is "Saving..." and "Saved". In this commit, we use Toasts to accomplish this.
(2) This is experimental. Therefore, only the add-dog and edit-dog save sequences have been instrumented to use toasts. 
(3) Variants have been defined for "brandInfo", "brandSuccess", and "brandError". Not much thought has been put into the styling. This can be revisited in time.
=> Use toasts to indicate status of saving/adding dog

e2e/_lib/pom/layout/toast-component.ts, e2e/user/user-can-add-dog.spec.ts, e2e/user/user-can-edit-dog.spec.ts, src/app/_lib/toast-delay.ts, src/app/user/(logged-in)/my-pets/add-dog/_components/add-dog-form.tsx, src/app/user/(logged-in)/my-pets/edit-dog/[dogId]/_components/edit-dog-profile-form.tsx, src/lib/utilities/async-sleep.ts
Update add-dog and edit-dog to show the "Adding..." and "Saving..." toasts for at least 1337 milliseconds before showing "Added" and "Saving" toasts.
=> Show in-progress toasts for a fixed duration.

src/app/user/(logged-in)/my-account/edit/_components/account-edit-form.tsx, src/app/user/(logged-in)/my-account/page.tsx, src/components/bark/bark-button.tsx, src/components/ui/button.tsx
(1) Some changes to BarkButton
(1.1) The `onClick` callback type now allows both asynchronous and synchronous functions.
(1.2) Added support for `disabled` buttons.
(1.3) Adjust the styling for `active:` and `hover:` states.
-(a) The earlier behaviour of switching between brand and brandInverse styles is now use to distinguish the `active:` state.
-(b) The `hover:` state is now a light opacity change.
(1.4) `md:w-[160px]` is removed because this makes the button size fixed for `md` screens and bigger—which became an issue when rendering buttons in small spaces on big screens. In general, I think the size of a button is related to the layout of the page and not the style of the button.
=> bark-button improvements

src/app/vet/(logged-in)/appointments/_actions/post-bark-report-data.ts, src/lib/bark/operations/op-submit-report.ts, src/lib/utilities/bark-code.ts, tests/bark/operations/op-submit-report.test.ts
(1) Renamed UNAUTHORIZED to ERROR_NOT_ALLOWED to follow the naming style of ERROR_NOT_LOGGED_IN.
=> Rename UNAUTHORIZED to ERROR_NOT_ALLOWED

e2e/_lib/sequences/do-create-appointment.ts, e2e/vet/vet-can-record-appointment-call-outcome.spec.ts, e2e/vet/vet-can-record-declined-call-outcome.spec.ts, src/app/vet/_lib/components/call-card.tsx, src/app/vet/_lib/hooks/use-owner-contact-details.ts, src/app/vet/_lib/models/scheduler-state.ts, src/components/bark/bark-user-contact-details.tsx, src/lib/bark/models/owner-contact-details.ts, src/lib/vet/actions/get-owner-contact-details.ts, src/lib/vet/vet-models.ts, tests/vet/get-owner-contact-details.test.ts
(1) User email is not useful for a call-list and it is also a login credential. Thus, in this commit, user emails are removed from the vet interfaces.
(2) Changes
(2.1) The BarkUserContactDetails component is updated to optionally accept user email. Email is provided in My Account, but not when a vet is viewing Owner Contact Details.
(2.2) The API for fetching owner contact details no longer provides user email.
=> Do not show user email to vets

e2e/_lib/pom/pages/vet-general-report-form.ts, e2e/vet/vet-can-edit-report.spec.ts, e2e/vet/vet-can-submit-report.spec.ts, e2e/vet/vet-can-view-report.spec.ts, src/app/vet/_lib/components/general-report-form.tsx, src/app/vet/_lib/components/report-card.tsx, src/app/vet/_lib/components/report-view.tsx, src/components/bark/bark-form.tsx
(1) This revises the form inputs in the General Report Form for Reported Ineligibility. Previously, the form framed the questions as one about Eligibility. This misses the point of Reported Ineligibility, which is to ask for additional reasons why a dog might be ineligible.
(2) This also include the following additional improvements.
(2.1) Improved validation for Reported Ineligibility. —(a) Ask for reason, then status, and then expiry date. —(b) Smartly check for reason before using status. E.g. if the reason is empty and the status is temporarily ineligible, the status recorded should still be NIL.
(2.2) Visit Time is changed to Visit Date.
(2.3) Improved cross-field validations. E.g. ineligibility expiry date is required when temporarily ineligible, and only when temporarily …
=> Revise the general report form

src/app/vet/_lib/components/report-card.tsx
Fix how we present reported ineligibility. They are now presented as badges. For the nil case, no badge is shown.
=> Present Reported Ineligibility correctly

src/app/user/(logged-in)/my-account/edit/_actions/post-my-account-details.ts, src/app/user/(logged-in)/my-account/edit/_components/account-edit-form.tsx
Server actions are POST handlers. Therefore, postMyAccountDetails should not redirect, but instead return a ERROR_NOT_LOGGED_IN code. The client component calling the server action should be the one doing the redirect.
=> Fix postMyAccountDetails

src/app/user/(logged-in)/info/page.tsx
DEA 1.1 or 1.2 are not exactly criteria. Some trickery was used to drop this, while maintaining the 3x3 grid.
=> Drop the DEA 1.1 or 1.2 criteria

e2e/_lib/pom/pages/user-edit-sub-profile-page.ts, e2e/_lib/pom/pages/user-view-dog-page.ts, e2e/user/user-can-view-report-and-edit-sub-profile.spec.ts, src/app/_lib/get-vet-form-options.ts, src/app/user/(logged-in)/my-pets/_lib/actions/post-sub-profile-update.ts, src/app/user/(logged-in)/my-pets/_lib/components/edit-dog-profile-form-controller.tsx, src/app/user/(logged-in)/my-pets/_lib/components/general-dog-form.tsx, src/app/user/(logged-in)/my-pets/_lib/components/sub-profile-form-controller.tsx, src/app/user/(logged-in)/my-pets/_lib/components/sub-profile-form.tsx, src/app/user/(logged-in)/my-pets/edit-dog/[dogId]/page.tsx, src/lib/bark/mappers/to-sub-profile.ts, src/lib/bark/models/dog-report-count.ts, src/lib/bark/models/sub-profile.ts, src/lib/bark/operations/op-fetch-dog-report-count.ts, src/lib/bark/queries/select-dog-report-count.ts, src/lib/user/actions/update-sub-profile.ts, src/lib/utilities/bark-code.ts, tests/_fixtures.ts
When a dog has a report, users are allowed to edit only some of the profile fields. These are known as sub profiles. In this commit, the edit-dog page is updated to consider the existing report count, and when this is non-zero, it will present to the user a form for editing a sub-profile.
=> Add support for editing sub profiles

src/app/user/(logged-in)/my-pets/_lib/components/general-dog-form.tsx, src/app/user/registration/_components/pet-form.tsx, src/components/bark/bark-status-block.tsx
This commit introduces two changes.
Firstly, the choice is now optional. So a "None" choice is always present.
Secondly, preferred vet options are presented so long as there is at least one vet option, not counting the None choice.
=> Adjust how vet options are presented and validated

e2e/_lib/ops/do-logout-sequence.ts, e2e/_lib/ops/do-schedule-appointment.ts, e2e/_lib/ops/do-submit-report.ts, e2e/user/user-can-view-report-and-edit-sub-profile.spec.ts, src/app/user/(logged-in)/my-account/edit/_components/account-edit-form.tsx, src/app/user/registration/_components/owner-form.tsx, src/app/user/registration/_components/pet-form.tsx, src/app/vet/_lib/components/call-card.tsx, src/app/vet/_lib/components/cancel-appointment-form.tsx, src/app/vet/_lib/components/general-report-form.tsx, src/components/bark/bark-button.tsx, src/components/bark/login/bark-login-form.tsx
(1) BarkButton changes to addressing the following issues:
-(a) Saving form changes instead of cancelling (vet edit report page).
-(b) Login form validates OTP field when user clicks "Send me an OTP".
(1.1) Update BarkButton props to be either for the link kind or the button kind. For the link kind, 'href' is specified and 'type' and 'onClick' can be omitted or must be set to undefined. For the button kind, 'type' must be specified, 'href' can be omitted or must be undefined, and 'onClick' is optional.
(1.2) Update all usage that isn't a link—i.e. no 'href'—to specify 'type' as either 'button' or 'submit'. Next Build will fail if we do not provide the correct props.
(2) Fixed some flaky UI tests. Specifically, the "user can view report and edit sub-profile" test. Here, the …
=> Fix BarkButton and unstable UI tests

e2e/_lib/ops/do-submit-report.ts, e2e/user/user-can-edit-incomplete-dog.spec.ts, e2e/user/user-can-set-weight-to-empty.spec.ts, e2e/user/user-can-view-report-and-edit-sub-profile.spec.ts, e2e/user/user-can-view-then-edit-dog.ts, e2e/vet/call-task-uses-latest-values.spec.ts, e2e/vet/vet-can-edit-report.spec.ts, e2e/vet/vet-can-submit-report.spec.ts, e2e/vet/vet-can-view-report.spec.ts, src/lib/encryption/hkdf-encryption-protocol.ts
Changes
- Optimise isProtocolFor to check just the string prefix for `_ENC2_`
Fixes
- Wait for toast to appear and then close it after submitting a report.
- Check for buttons after checkURL. (What we really need is checkReady.)
=> Address UI Test Stability

db/V4__ref_latest_values.sql, tests/schema/latest-values.test.ts
The latest_values view is updated to use the latest non-null weight. This solves the issue whereby latest weight is stuck as null until a report exists with visit time more recent than the dog's profile modification time.
=> BARK-7443: Use latest non-null weight

e2e/_lib/ops/do-register.ts, e2e/visitor/visitor-can-register.spec.ts
Since BARK-84, pregnancy options are no longer clickable when the dog gender is MALE. So we must check if the options are clickable before trying to click them in the UI tests.
=> BARK-14: UI Test - Check if pregnancy options are enabled.

src/lib/app.ts, src/lib/bark/daos/report-dao.ts, src/lib/bark/operations/op-edit-report.ts, src/lib/bark/operations/op-fetch-report.ts, src/lib/bark/operations/op-fetch-reports-by-vet-id.ts, src/lib/bark/operations/op-submit-report.ts, src/lib/bark/services/dog-profile-service.ts, tests/_fixtures.ts, tests/bark/services/dog-profile-service.test.ts
Require ReportDao to be constructed from a DbPool so that it can be constructed once in AppFactory and injected into the services that require ReportDao. Optionally, where the DAO needs to operate within transactions, it can accept a conn arg.
=> BARK-35: Injectable ReportDao
