src/lib/app.ts
Changes
(1) AppFactory was updated to cache promises of singletons. This way their singleton status is guaranteed even in an async environment. This is because a Promise can always be synchronously created.
=> PromiseMe - Update AppFactory to cache promises of singletons

src/lib/route-path.ts, tests/RoutePath.test.ts, tests/routes.test.ts
Examples of route paths with param.
=> RoutePaths - Add USER_VIEW_DOG and USER_EDIT_DOG paths

src/app/user/login/page.tsx, src/lib/app.ts, src/lib/user/user-account-service.ts, src/lib/user/user-actor-factory.ts, src/lib/user/user-actor.ts, tests/UserAccountService.test.ts, tests/UserActor.test.ts, tests/UserActorFactory.test.ts, tests/_fixtures.ts
Changes
(1) A new UserAccountService service is introduced. This is responsible for consolidating operations pertaining to user accounts.
(2) As such, the UserActor and UserActorFactory were updated to depend on UserAccountService.
(3) Some refactoring of test fixtures and some bug fixes therein.
=> UserAccountService - Impl service for user accounts

src/app/user/registration/_components/donor-form.tsx, src/app/user/registration/_components/pet-form.tsx, src/components/bark/bark-form.tsx, src/lib/user/registration-handler.ts, tests/registration-handler.test.ts
Work on breed input, vet input and pet birthday input.
- change vet field to be undefined if no vets are found.
- If only 1 vet or no vet is found, will not show vet input.
- added test for registration-handler, 'RegistrationHandler without vet id', please help to check if its correct!
- update date input to be type able for accessibility.
- change breed for select to text input
=> Fix input fields that are flagged out

src/app/user/registration/_components/donor-form.tsx, tests/_fixtures.ts
Changes
- Fix the return types in fixtures
- Fix the `as Type` statements.
=> Fixes for no-enums

src/app/admin/(logged-in)/dashboard/_components/incomplete-profiles.tsx, src/app/admin/(logged-in)/dashboard/page.tsx, src/lib/admin/actions/get-incomplete-profiles.ts, src/lib/admin/admin-actor-factory.ts, src/lib/admin/admin-actor.ts, src/lib/admin/admin-models.ts, src/lib/app.ts, tests/_fixtures.ts, tests/admin/AdminActor.test.ts, tests/admin/get-incomplete-profiles.test.ts
Add missing fields to incomplete profile type.
Remove old implementation for fetching incomplete profiles.
Update the admin actor and factory configuration.
=> Clean up admin

scripts/setup-dev-data.js, src/app/api/dangerous/sql/route.ts
CHANGES
* feat: new dangerous api for running sql ⚠️ 
* refactor: replace all callbacks with promises
* refactor: wrap main flow inside a main() function
* feat: purge data before adding new records
* this makes it possible to run the script without rebuilding the database from scratch.
* previously there would have been conflicts with the email addresses.
* feat: add dog vet preferences
* feat: add APPOINTMENT calls for the first 3 users
=> Update setup dev script

README.md, src/lib/app-env.ts, src/lib/app.ts, src/lib/user/actions/get-my-dog-details.ts, src/lib/user/actions/update-my-dog-details.ts, src/lib/user/actions/update-my-dog-registration.ts, src/lib/user/user-actor.ts, src/lib/user/user-models.ts, tests/_fixtures.ts, tests/schema/dog-participation-check.test.ts, tests/user/get-my-dog-details.test.ts, tests/user/update-my-dog-details.test.ts, tests/user/update-my-dog-registration.test.ts
CHANGES
- feat: add dogNonParticipationReason to MyDogDetails, MyDogDetailsUpdate, and MyDogResgistrationUpdate models.
- feat: update getMyDogDetails, updateMyDogDetails, and updateMyDogRegistration accordingly.
- feat: new `BARKBANK_TEXT_SECRET` environment variable and APP textEncryptionService. This is used to encrypt/decrypt `dog_encrypted_reason`.
=> Support for non-participation reason

Makefile, scripts/test_no_wip_tasks_remaining.sh, src/lib/app.ts, src/lib/vet/actions/get-available-dogs.ts, src/lib/vet/vet-actor-factory.ts, src/lib/vet/vet-actor.ts, src/lib/vet/vet-models.ts, tests/_fixtures.ts, tests/vet/VetActorFactory.test.ts, tests/vet/get-available-dogs.test.ts
- Implement getAvailableDogs(VetActor): Promise<AvailableDog[]>.
- Refactor constructors and configs for VetActor and VetActorFactory.
=> implement get-available-dogs for vet-actors

src/lib/data/user-mapper.ts, src/lib/vet/actions/get-available-dogs.ts, src/lib/vet/actions/get-owner-contact-details.ts, src/lib/vet/vet-models.ts, tests/vet/get-available-dogs.test.ts, tests/vet/get-owner-contact-details.test.ts
- Implement getOwnerContactDetails for VetActor.
- Remove userId from AvailableDog model. It is not necessary because vets should request for owner details by dogId so that preferred vet can be checked.
=> implement get-owner-contact-details for vet-actors

scripts/setup-dev-data.js, src/app/vet/(logged-in)/schedule-appointments/page.tsx, src/lib/data/db-dogs.ts, src/lib/vet/actions/get-owner-contact-details.ts, src/lib/vet/vet-models.ts, tests/vet/get-owner-contact-details.test.ts
This is the last time the vet contacted the user.
=> add vet-user-last-contacted-time

db/V2__ref_tables.sql, db/V4__ref_latest_values.sql, src/lib/data/db-models.ts, src/lib/data/db-reports.ts, tests/_fixtures.ts
A column was added to the reports table to record when blood donation occurred during an appointment.
Changes
- Add dog_did_donate_blood column to reports table
- Add dogDidDonateBlood boolean field to ReportSpec
- Update dbInsertReport
=> Add dog_did_donate_blood column to the reports tables

db/V4__ref_latest_values.sql, db/V5__ref_dog_statuses.sql, tests/schema/dog-statuses.test.ts, tests/schema/latest-values.test.ts
Add latest blood donation time to the latest values view.
Update the dog statuses view to consider the latest blood donation time when evaluating medical eligibility.
=> Add latest blood donation time and consider it when evaluating medical eligibility

e2e/_lib/pom/pages/user-my-account-edit-page.ts, e2e/_lib/pom/pages/user-my-account-page.ts, e2e/user/user-can-cancel-edit-account.spec.ts, e2e/user/user-can-edit-account.spec.ts, src/app/user/(logged-in)/my-account/edit/_components/account-edit-form.tsx, src/app/user/(logged-in)/my-account/edit/page.tsx
(1) Fixed cancel button for edit user account details form
(2) Added e2e test for cancelling an edit
(3) Added e2e test for saving and edit
=> Fix cancel edit user account button

README.md, src/lib/user/actions/get-dog-statuses.ts, src/lib/user/user-models.ts, tests/_time_helpers.ts, tests/schema/latest-values.test.ts, tests/user/get-dog-statuses.test.ts
(1) Implement the getDogStatuses(UserActor, dogId) user-action function.
(2) Update README. Include some information about how to run the Playwright tests.
=> Impl getDogStatuses(UserActor, dogId)

.github/workflows/run-tests.yml, scripts/test_code_is_pretty.sh, scripts/test_git_status_is_empty.sh, src/lib/user/actions/add-my-dog.ts
(1) Update the run-tests workflow to use postgres 15.2
(2) Move prettier checks into a standalone script to better control when diff and status are shown.
=> Improvements for the run-tests workflow

src/app/user/(logged-in)/my-account/edit/_components/account-edit-form.tsx, src/components/ui/button.tsx
Implemented for edit user page at first but realised that other Button variants shared this same issue hence the additional changes to variants not used in user edit page.
=> Fix: Button styles for mobile view 

src/app/user/registration/_components/owner-form.tsx, src/components/bark/bark-form.tsx
Handle when post-otp-request returns non-OK in the registration flow by asking the user to request another.
=> Handle failed OTP sends

e2e/_lib/e2e-test-utils.ts, e2e/_lib/pom/core/pom-component.ts, e2e/_lib/pom/core/pom-dynamic-page.ts, e2e/_lib/pom/core/pom-object.ts, e2e/_lib/pom/core/pom-page.ts, e2e/_lib/pom/pages/vet-schedule-page.ts, e2e/vet/vet-can-record-appointment-call-outcome.spec.ts, e2e/vet/vet-can-record-declined-call-outcome.spec.ts, src/app/vet/(logged-in)/schedule/_components/appointment-scheduler.tsx, src/app/vet/(logged-in)/schedule/_components/call-card.tsx, src/app/vet/(logged-in)/schedule/_components/dog-card.tsx, src/app/vet/(logged-in)/schedule/_components/scheduler-badges.tsx
(1) Support recording of Scheduled and Declined outcomes on mobile screens.
(2) The call card is rendered directly within the dog card.
This was found to be the simplest approach.
Additionally, the user is able to see both dog and owner details.
=> Mobile vet appointment scheduler

db/V2_1__enable_rls.sql, db/V4__ref_latest_values.sql, db/V5__ref_dog_statuses.sql, tests/_db_helpers.ts
(1) Copy recent changes to barkbank-schema (RLS related) to the local reference schema in barkbank-pawtal.
(2) Update db helpers to include the new file when setting up the test database before each test.
=> sync db schema

src/lib/bark/models/appointment-situation.ts, src/lib/bark/models/bark-report-data.ts, src/lib/bark/models/bark-report-metadata.ts, src/lib/bark/models/bark-report.ts, src/lib/bark/models/encrypted-bark-appointment.ts, src/lib/bark/models/encrypted-bark-report-data.ts, src/lib/bark/models/encrypted-bark-report.ts, src/lib/bark/queries/select-appointment-situation.ts, src/lib/bark/queries/select-report.ts
(1) Use Zod to specify schemas for all models in lib/bark/models
(2) Use schemas to parse all SQL query outputs.
=> Zod schemas for Bark Models

e2e/_lib/pom/core/pom-page.ts, e2e/_lib/pom/layout/nav-component.ts, e2e/_lib/pom/pages/vet-appointments-list-page.ts, e2e/_lib/pom/pages/vet-cancel-appointment-page.ts, e2e/_lib/pom/pages/vet-submit-report-page.ts, e2e/_lib/sequences/do-create-appointment.ts, e2e/vet/vet-can-cancel-appointment.spec.ts, e2e/vet/vet-can-submit-report.spec.ts, scripts/setup-dev-data.js, src/app/vet/(logged-in)/appointments/_actions/post-cancel-appointment.ts, src/app/vet/(logged-in)/appointments/_components/cancel-report-form.tsx, src/app/vet/(logged-in)/appointments/_components/submit-report-form.tsx, src/app/vet/(logged-in)/appointments/cancel/[appointmentId]/page.tsx, src/app/vet/(logged-in)/appointments/list/page.tsx, src/app/vet/(logged-in)/appointments/submit/[appointmentId]/page.tsx, src/lib/route-path.ts, tests/bark/operations/op-cancel-appointment.test.ts, tests/bark/operations/op-submit-report.test.ts
(1) Implement the Cancel Appointment Page
(2) Additionally, UI tests were written for the following use cases:
-(a) vet can cancel appointment
-(b) vet can submit report
=> Implement Cancel Appointment Page

.github/workflows/x-checks.yml, src/app/vet/(logged-in)/appointments/_actions/post-bark-report-data.ts, src/lib/bark/models/encrypted-dog-id-info.ts
(1) npm run build was failing due to a type mismatch. That answers one question! That builds do fail when there are typescript issues! To address this we did two things. First, we added to github a job that runs `npm run build`. Second, we addressed the actual issue.
=> Fix broken build

e2e/_lib/pom/pages/vet-appointment-cancel-page.ts, e2e/_lib/pom/pages/vet-appointment-list-page.ts, e2e/_lib/pom/pages/vet-appointment-submit-report-page.ts, e2e/_lib/pom/pages/vet-general-report-form.ts, e2e/_lib/pom/pages/vet-report-edit-page.ts, e2e/_lib/pom/pages/vet-report-list-page.ts, e2e/_lib/pom/pages/vet-report-view-page.ts, e2e/_lib/sequences/do-create-appointment.ts, e2e/vet/vet-can-cancel-appointment.spec.ts, e2e/vet/vet-can-edit-report.spec.ts, e2e/vet/vet-can-submit-report.spec.ts, e2e/vet/vet-can-view-report.spec.ts, src/app/_lib/constants.ts, src/app/globals.css, src/app/vet/(logged-in)/appointments/list/page.tsx, src/app/vet/(logged-in)/reports/view/[reportId]/page.tsx, src/app/vet/_lib/components/dog-card.tsx, src/app/vet/_lib/components/edit-report-form.tsx, src/app/vet/_lib/components/report-card.tsx, src/app/vet/_lib/components/report-view.tsx, src/components/bark/bark-user-contact-details.tsx
(1) Implemented the page for viewing a report. This is for vets.
(2) Other Changes
(2.1) The link to edit a report in the Report List page is removed. Instead, clicking on a card brings the Vet user to the Report View page. The Report View page has Back and Edit buttons. The Edit button will bring the Vet to the Report Edit page. The UI test was updated to go through this process.
(2.2) Defined a set of x-card classes in global CSS.
=> Implement report view for vets

e2e/_lib/pom/pages/vet-report-edit-page.ts, src/app/vet/(logged-in)/appointments/list/page.tsx, src/app/vet/(logged-in)/reports/list/page.tsx, src/app/vet/_lib/components/appointment-card.tsx, src/app/vet/_lib/components/appointment-list.tsx, src/app/vet/_lib/components/appointment-scheduler.tsx, src/app/vet/_lib/components/dog-card.tsx, src/app/vet/_lib/components/general-report-form.tsx, src/app/vet/_lib/components/report-card.tsx, src/app/vet/_lib/components/report-list.tsx, src/app/vet/_lib/components/search-input.tsx, src/lib/utilities/get-matching-items.ts, tests/utilities/get-matching-items.test.ts
(1) Support search in vet call list, appointment list, and report list.
(2) Changes
(2.1) Implement a generic getMatchingItems function.
(2.2) Use getMatchingItems to support search in the vet pages that list items.
(3) Other Changes
(3.1) Change the button text from "Edit Report" to "Save Changes". Feels more natural.
=> Support search in vet call list, appointment list, and report list

src/lib/bark/models/call-task.ts, src/lib/bark/queries/select-call-tasks-by-vet-id.ts, tests/bark/operations/op-fetch-call-tasks-by-vet-id.test.ts
Add dog last contacted time and owner last contacted time to CallTask.
=> Add last contacted times to call task

src/app/vet/_lib/components/appointment-scheduler.tsx, src/app/vet/_lib/components/dog-card.tsx, src/app/vet/_lib/components/scheduler-badges.tsx, src/app/vet/_lib/components/sort-option-selector.tsx, src/lib/utilities/comparators.ts
(1) Support sorting by dog last contacted time.
(2) Support sorting by owner last contacted time.
(3) Show a recently contacted badge when dog last contacted time is within the last 7 days.
=> present-last-call-information

src/lib/bark/models/owner-info.ts, src/lib/bark/operations/op-fetch-reports-by-dog-id.ts, src/lib/bark/queries/cte-encrypted-bark-report.ts, src/lib/bark/queries/select-owner-by-dog-id.ts, src/lib/bark/queries/select-report.ts, src/lib/bark/queries/select-reports-by-dog-id.ts, src/lib/bark/queries/select-reports-by-vet-id.ts, src/lib/services/encryption.ts, tests/bark/operations/op-fetch-reports-by-dog-id.test.ts
Implement bark operation opFetchReportsByDogId to retrieve reports for the View Dog page.
=> Impl opFetchReportsByDogId

Makefile, package-lock.json
Address the security issue raised by dependabot linked below. This was done via `npm audit fix`. Additionally, some refactoring was done to the Makefile.
https://github.com/barkbank/barkbank-pawtal/security/dependabot/3
=> Address security issue raised by dependabot

e2e/_lib/pom/pages/user-my-account-page.ts, e2e/user/user-can-cancel-edit-account.spec.ts, e2e/user/user-can-edit-account.spec.ts, e2e/user/user-can-view-account.spec.ts, e2e/visitor/visitor-can-register.spec.ts, src/components/bark/bark-user-contact-details.tsx
Display user contact values in disabled input elements to support the presentation of long emails.
=> Display user contact values in disabled input element

src/app/user/(logged-in)/my-pets/_lib/components/dog-card.tsx, src/app/user/(logged-in)/my-pets/_lib/dog-viewer/reports-section.tsx, src/app/vet/_lib/components/dog-card.tsx, src/app/vet/_lib/components/report-card.tsx
(1) Some simple UI treatments to make cards feel lively and clickable.
- Lively - Highlight cards by changing their background colour upon hover.
- Clickable - Change the cursor to a pointer upon hover.
(2) The following cards were updated:
- Cards in the My Pets view.
- Cards in the Reports section of the View Dog page.
- Cards in the Vet's scheduler—a.k.a. call list.
- Cards in the Vet's reports tool.
=> Lively Cards

src/app/admin/(logged-in)/dashboard/_components/incomplete-profiles.tsx, src/app/user/(logged-in)/my-pets/_lib/components/general-dog-form.tsx, src/lib/bark/enums/dog-gender.ts, src/lib/bark/models/bark-appointment.ts, src/lib/bark/models/call-task.ts, src/lib/bark/models/dog-id-info.ts, src/lib/bark/models/dog-profile.ts, tests/_fixtures.ts, tests/bark/_given.ts
In this commit we remove the UNKNOWN option for dog gender. Consequently, Specified Dog Gender was no longer necessary. Thus that too was removed.
=> BARK-20: Restrict Dog Gender to just Male and Female

Makefile, scripts/make-ticket.sh
Enhanced version of `make ticket` that selects random ticket numbers from exponentially larger spaces when there is a collision. For example, it will first try (1, 8). If there are collisions it will try spaces (9, 24), (25, 56), ...
=> BARK-5: Enhanced version of make ticket

env.template, src/lib/app.ts, src/lib/barkbank-env.ts, src/lib/data/db-utils.ts, src/middleware.ts, tests/authDangerous.test.ts
(1) Align enumerations with NODE_ENV values and adopt the same interpretations (Ref1). I.e., the values are development, test, and production.
(2) Adopt the following behaviours:
-(a) Allow use of dangerous APIs only in development and in test.
-(b) Log from db-utils only when in development.
-(c) Require a CA cert file to be specified when in production. This forces SSL connection to DB.
-(d) Use development OTP service in development and test environments.
Ref1: https://www.geeksforgeeks.org/what-is-node_env-in-node-js/
=> BARK-2: Revise BARKBANK_ENV

src/app/user/(logged-in)/my-pets/_lib/components/dog-card.tsx
Just needed to add w-full to the parent div.
=> BARK-7: Fix text alignment in My Pets Mobile

src/app/examples/autocomplete/_lib/breed-form.tsx, src/app/examples/autocomplete/page.tsx, src/app/examples/layout.tsx, src/components/bark/bark-form-autocomplete.tsx
A demo is available in /examples/autocomplete. This can be accessed in development only.
=> BARK-3: Impl BarkFormAutocomplete component

e2e/_lib/pom/pages/user-add-dog-page.ts, e2e/_lib/pom/pages/user-edit-dog-page.ts, src/app/_lib/field-schemas/required-date-field.ts, src/app/user/(logged-in)/my-pets/_lib/components/general-dog-form.tsx, src/app/user/registration/_components/pet-form.tsx, src/app/vet/_lib/components/general-report-form.tsx
(1) Add DD MMM YYYY placeholder to birthday fields and report visit date fields.
(2) Align dog field names in Pet Form and General Dog Form.
=> BARK-1: Add DD MMM YYYY placeholder to date fields

db/V2_1__enable_rls.sql, db/V2__ref_tables.sql, e2e/_lib/models/known-vet-account.ts, e2e/_lib/ops/do-login-known-vet-account.ts, e2e/_lib/utils/get-known-vet-account.ts, e2e/vet/vet-can-login-using-alternative-vet-account.spec.ts, scripts/setup-dev-data.js, src/app/vet/(logged-in)/layout.tsx, src/lib/app.ts, src/lib/bark/operations/op-get-vet-id-by-email.ts, src/lib/bark/queries/select-vet-id-list-by-email.ts, src/lib/data/db-vets.ts, src/lib/utilities/bark-code.ts, src/lib/vet/vet-actor-factory.ts, src/lib/vet/vet-actor.ts, tests/_fixtures.ts, tests/bark/operations/op-get-vet-id-by-email.test.ts, tests/data/db-vets.test.ts
Relates to schema migration https://github.com/barkbank/barkbank-schema/pull/39
=> BARK-42: Support multiple login emails per vet

src/lib/app.ts, src/lib/services/email-hash-service.ts, tests/_fixtures.ts
Vet logins will be addressed by BARK-27
=> BARK-52: Convert emails to lower case before hashing

src/app/admin/(logged-in)/tools/page.tsx, src/app/admin/(logged-in)/tools/rpc/_lib/post-admin-command.ts, src/app/admin/(logged-in)/tools/rpc/page.tsx, src/components/bark/bark-form-text-area.tsx, src/lib/admin/rpc/admin-command-dispatcher.ts, src/lib/admin/rpc/admin-command.ts, src/lib/admin/rpc/command-index.ts, src/lib/admin/rpc/commands/add-vet-accounts.ts, src/lib/admin/rpc/commands/list-vet-accounts-by-vet.ts, src/lib/admin/rpc/commands/list-vet-clinics.ts, src/lib/bark/operations/op-list-vet-accounts-by-vet.ts, src/lib/route-path.ts
Implement an Admin RPC Commands tool. A quick and dirty way to add admin capabilities.
=> BARK-31: Admin RPC Commands

src/app/_components/header-items.tsx, src/components/bark/login/bark-login-page.tsx
- Pawtal branding in the middle of the header bar
- Remove link to Visit FAQ
- ExternalLink icon for Visit Website
- Adjust the size of headers within the login page
=> BARK-15: Harmonise Pawtal and WebFlow

Makefile, e2e/_lib/ops/do-register.ts, e2e/_lib/pom/core/pom-page.ts, e2e/_lib/pom/pages/user-registration-owner-form-page.ts, e2e/_lib/pom/pages/user-registration-page.ts, e2e/_lib/pom/pages/user-registration-pet-form-page.ts, e2e/_lib/pom/pages/user-registration-success-page.ts, e2e/visitor/visitor-can-register.spec.ts, src/app/user/registration/_actions/post-registration-request.ts, src/app/user/registration/_components/donor-form.tsx, src/lib/bark/operations/op-send-welcome-email.ts
(1) There are two places where mention of preferred vet is inhibited:
-(a) In the success step of the registration flow, mention of an upcoming outreach by a preferred vet is inhibited when no preferred vet has been selected.
-(b) In the welcome email sent to donors, mention of a preferred vet is omitted when no preferred vet has been selected.
(2) Includes refactoring to split UserRegistrationPage into UserRegistrationPetFormPage, UserRegistrationOwnerFormPage, and UserRegistrationSuccessPage.
=> BARK-89: Only mention that a vet will reach out when a preferred vet has been selected

src/app/_components/root-footer.tsx, src/app/logout/_components.tsx
It is based on login status and pathname.
=> BARK-62: Adjust when padding beneath footer needs to be applied

src/components/bark/login/bark-login-page.tsx
=> BARK-78: Fix footer for login pages

db/V2__ref_tables.sql, src/app/_components/tracker.tsx, src/lib/bark/daos/pawtal-events-dao.ts, src/lib/bark/models/tracker-models.ts, tests/bark/daos/pawtal-events-dao.test.ts
Related migration - https://github.com/barkbank/barkbank-schema/pull/48
=> BARK-125: Capture query strings in Pawtal Events

db/V2__ref_tables.sql
Relates to https://github.com/barkbank/barkbank-schema/pull/49
=> BARK-111: Update schema

db/V2_1__enable_rls.sql, db/V2__ref_tables.sql, src/lib/app.ts, src/lib/bark/operations/op-index-donor-snapshots.ts, src/lib/bark/queries/insert-donor-snapshot.ts, src/lib/bark/queries/select-1-as-ping.ts, src/lib/bark/services/cron-service.ts, tests/bark/operations/op-index-donor-snapshots.test.ts
Relates to https://github.com/barkbank/barkbank-schema/pull/51
=> BARK-120: Index donor_snapshots

src/lib/admin/admin-actor-factory.ts, src/lib/admin/admin-actor.ts, src/lib/vet/vet-actor-factory.ts, src/lib/vet/vet-actor.ts, tests/_fixtures.ts
Use `constructor(private args: {...})` like in UserActor.
=> BARK-180: Standardise constructors for VetActor and AdminActor

Makefile, e2e/_lib/pom/pages/user-add-dog-page.ts, e2e/_lib/pom/pages/user-edit-dog-page.ts, e2e/_lib/pom/pages/user-registration-pet-form-page.ts, e2e/_lib/pom/pages/user-view-report-page.ts, e2e/_lib/pom/pages/vet-general-report-form.ts, e2e/_lib/pom/pages/vet-report-list-page.ts, e2e/user/user-can-view-report-and-edit-sub-profile.spec.ts, e2e/vet/call-task-uses-latest-values.spec.ts, e2e/vet/vet-can-edit-report.spec.ts, e2e/vet/vet-can-submit-report.spec.ts, e2e/vet/vet-can-view-report.spec.ts, src/app/_components/report-view.tsx, src/app/_lib/formatters.ts, src/app/user/(logged-in)/info/page.tsx, src/app/user/(logged-in)/my-pets/_lib/components/general-dog-form.tsx, src/app/user/registration/_components/pet-form.tsx, src/app/vet/_lib/components/general-report-form.tsx, src/app/vet/_lib/components/report-card.tsx
Singapore's canine blood typing tests check for DEA 1 in general, rather than specific subtypes like DEA 1.1 or DEA 1.2. Therefore, we plan to update Bark Bank to align with this broader typing approach.
=> BARK-69: Update frontend to display DEA 1 instead of DEA 1.1
